### PR TITLE
DE54258: Added tests for security filter chain.

### PR DESCRIPTION
**Pull request by irinaepshteyn**

### CODE REVIEW

**Comment by irinaepshteyn** [comment]
Tests PASSed:
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/345/

https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/1156/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/1157/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/1158/
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/1160/

**Review by anubhavi25 — CHANGES_REQUESTED** [review]
These changes look good however tests for the `/health` endpoint are missing since it also requires authorization to get statuses of the full dependency graph.

**Comment by VoollaSandeepKumar** [comment]
Changes look good.

**Comment by irinaepshteyn** [comment]
PR is ready for final review
- Updated token lib version to 3.3.3-SNAPSHOT pickup the fix for handling token time validation failure
- Added tests for health endpoint

**Comment by irinaepshteyn** [comment]
Tests PASSed:
https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/347/

https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-integration-pullrequest/1161 - 1164

**Review by anubhavi25 — APPROVED** [review]

**Pull request merged**
