### PR TITLE
US49050: Modified to consume titan1.1

### PR DESCRIPTION
**Pull request by irinaepshteyn**

### CODE REVIEW

**Comment by matiasa123** [comment]
[Build Status](https://predix1.jenkins.build.ge.com/job/Predix-Security/job/acs-build-n-test-pullrequest/677/)

**Comment by irinaepshteyn** [comment]
Integration tests for cloud-titan profile failed.  ACS application failed to start with the following exception:
com.thinkaurelius.titan.core.TitanException: StorageBackend version is incompatible with current Titan version: storage=1.0.0 vs. runtime=1.1.0-SNAPSHOT

**Comment by matiasa123** [comment]
[Build Status](https://predix1.jenkins.build.ge.com/job/Predix-Security/job/acs-build-n-test-pullrequest/679/)

Build Success

**Comment by matiasa123** [comment]
We originally were planning on using a titan1.1 that we built ourselves but we found titan1.1 snapshot on the thinkaurelius maven repo

**Pull request merged**
