### PR TITLE
US161387: Refactored service POM to isolate predix profile.

### PR DESCRIPTION
**Pull request by irinaepshteyn**
- Removed duplicate plugin configurations.
- Renamed profiles to better reflect their purpose.

### CODE REVIEW

**Comment by irinaepshteyn** [comment]
Final maven profiles and plugin configurations in service/pom.xml:

public (Default) 
* maven-compiler-plugin: exclude audit and audit tests    
* maven-surefire-plugin:
-- report directory: surefire-reports
-- SPRING_ACTIVE_PROFILES = h2,public,simple-cache
* maven-failsafe-plugin:
-- report directory: surefire-reports
--SPRING_ACTIVE_PROFILES = h2,public,simple-cache
-- exclude controller tests for graph

public-titan
* maven-compiler-plugin: exclude audit and audit tests    
* maven-surefire-plugin:
-- report directory: surefire-reports-titan
-- SPRING_ACTIVE_PROFILES = h2,public,simple-cache,titan
* maven-failsafe-plugin:
-- report directory: surefire-reports-titan
-- SPRING_ACTIVE_PROFILES = h2,public,simple-cache,titan
-- exclude non-hierarchical controller tests

predix-titan
* maven-surefire-plugin:
-- report directory: surefire-reports-titan
-- SPRING_ACTIVE_PROFILES = h2,public,simple-cache,titan
* maven-failsafe-plugin:
-- report directory: surefire-reports-titan
-- SPRING_ACTIVE_PROFILES = h2,public,simple-cache,titan
-- exclude non-hierarchical controller tests

**Comment by irinaepshteyn** [comment]
All tests PASSED
https://predix1.jenkins.build.ge.com/buildStatus/icon?job=Predix-Security/ACS/ACS-PullRequest/acs-build-pullrequest&build=261

https://predix1.jenkins.build.ge.com/buildStatus/icon?job=Predix-Security/ACS/ACS-PullRequest/acs-integration-pullrequest&build=861
https://predix1.jenkins.build.ge.com/buildStatus/icon?job=Predix-Security/ACS/ACS-PullRequest/acs-integration-pullrequest&build=862
https://predix1.jenkins.build.ge.com/buildStatus/icon?job=Predix-Security/ACS/ACS-PullRequest/acs-integration-pullrequest&build=863
https://predix1.jenkins.build.ge.com/buildStatus/icon?job=Predix-Security/ACS/ACS-PullRequest/acs-integration-pullrequest&build=864

**Comment by anubhavi25** [comment]
**Update: After talking to @irinaepshteyn about this, if no test code uses beans conditionally wired by the `predix` profile, this comment can be ignored and we can go with the original approach mentioned in the comment above**

Unless I'm missing something, shouldn't we change the Predix-related Maven profiles to the following?:

Maven profile: `predix`
- Report directory: `surefire-reports`
- Active Spring profiles: `SPRING_ACTIVE_PROFILES=h2,predix,simple-cache`

Maven profile: `predix-titan`
- Report directory: `surefire-reports-titan`
- Active Spring profiles: `SPRING_ACTIVE_PROFILES=h2,predix,simple-cache,titan`

Key things here are:
- Add the `predix` Maven profile
- Use the `predix` instead of the `public` Spring profile for all Predix-related Maven profiles so that all Predix-related integration test Maven profiles (`predix-{local,cloud}`, `predix-{local,cloud}-titan`) use a version of ACS built with the `predix` Spring profile

**Comment by anubhavi25** [comment]
Also please include the story number in either the pull request title or the commit message so it's easy to track what happened from just looking at the commit history on the base branch.

**Comment by irinaepshteyn** [comment]
@anubhavi25, as discussed earlier, predix spring profile is not required for ACS service unit and controller tests as it will wire predix related beans (metering, zac token service, etc.).  This functionality is covered by the corresponding integration tests.  

However, predix maven profile is required to compile and run unit tests for audit.

If you agree, please approve the pull request.

**Review by anubhavi25 — APPROVED** [review]
Please rerun the pull request pipeline since the latest rebase includes changes that were not tested (i.e. `service/src/test/java/com/ge/predix/controller/test/ConfigureEnvironment.java` differs from the file in the workspace of the build related to this PR: https://predix1.jenkins.build.ge.com/job/Predix-Security/job/ACS/job/ACS-PullRequest/job/acs-build-pullrequest/ws/service/src/test/java/com/ge/predix/controller/test/ConfigureEnvironment.java/*view*/ ).

If tests pass, feel free to merge this in.

**Pull request merged**
